### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by Keirua** [ncase/crowds#1]
... I'm working on it !

 - [x] 0. Introduction
 - [x] 1. Connections
 - [x] 2. Contagions
 - [x] 3. Contagions complexes
 - [x] 4. Liens &amp; Ponts
 - [x] 5. Le monde est petit
 - [x] 6. En conclusion...
 - [x] 7. Crédits
 - [x] ★ Mode bac à sable ! ★
 - [x] Références (~1000words on its own)
 - [x] Bonus (~700w)

**Comment by ncase** [comment]
Merci beaucoup! 🙌

**Comment by Fangh** [comment]
Comment puis-je t'aider ?

**Comment by Keirua** [comment]
Hi @Fangh, there is a `french-translation` branch on my fork: https://github.com/Keirua/crowds/tree/french-translation
We can work on different sections at the same time: I started at the beginning, maybe you can start from the end and work backward? No idea what the best workflow could be, but one option is to have intermediate PRs that I can merge once you feel you have enough content to include in the branch.

**Comment by Doshirae** [comment]
Do you want a 3rd hand to help ?

**Comment by Keirua** [comment]
Sure! Feel free to translate some chapters as well.

**Comment by Mokamoka123** [comment]
Do you need more help ? :)

**Comment by Falpermax** [comment]
Je veux participer aussi !
