### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by Niker107** [ncase/crowds#6]
Quite happy that I'll be able to work on a translation for a Nicky Case game.

**Comment by Agamidae** [comment]
Вам помочь? Могу вычитать перевод, как закончите

**Comment by Niker107** [comment]
Буду рад помощи!

**Comment by toby3d** [comment]
Я также [приступил к переводу](https://github.com/NotDotTeam/crowds). Буду рад коллаборации!

**Comment by Niker107** [comment]
Может быть разделим работу? Например Вы переведете главы 4, 5, 6, а я главы до этого (и титры).

**Comment by Agamidae** [comment]
Вы бы, может, создали общий документ на Гугл Докс? Или перевод на Нотабеноиде — у меня есть инвайты, если надо. Не переведёт же toby весь текст за час.

**Comment by toby3d** [comment]
Дык, я начал заниматься переводом в первые часы после релиза. Не вижу нужды в вополнительных внешних инструментов, если есть GitHub.

**Comment by Niker107** [comment]
Увы, недавно понял, что заниматься переводом для этого проекта у меня недостаточно свободного времени, и toby по-видимому уже сделал гораздо больше прогресса. В общем, желаю удачи и советую всем, кто хочет помочь, сделать это в кооперации с одной из существующих репо (как у toby).

**Comment by toby3d** [comment]
Предлагаю либо закрыть, либо перевесить issue на меня. Я планирую ещё какое-то время дополнять и подправлять перевод.

**Comment by Niker107** [comment]
@toby3d Хорошо, issue я закрыл. Не увидел только, где можно перевесить.
