### ISSUE TITLE
Improvements for Vietnamese translation

### ISSUE THREAD

**Issue by MrN83** [ncase/crowds#71]
This issue is for tracking the recent work done to improve the Vietnamese translation, which was started as this issue: ["Vietnamese(vi) translation #12"](https://github.com/ncase/crowds/issues/12).

**Comment by NOVAglow** [comment]
Hi @MrN83.

I've created [my fork](http://github.com/NOVAglow/crowds).

I uploaded my fix. If you have time, please translate the reference boxes for me?

Thanks a lot. :+1:

**Comment by MrN83** [comment]
I have translated the reference boxes but I still need to complete the reviewing and touching up of a few more chapters. I will get stuff done one bit at a time and will check in to your fork several more times. I'll then do a final sanity check.

Happy to work on this project :).

**Comment by NOVAglow** [comment]
@MrN83 I'm glad to hear that!

**Comment by MrN83** [comment]
Just to let you know I have basically finished reviewing and touching up the translation. I haven't had the time to proof-read the entire thing end-to-end. I will hopefully get some time to do that in a couple of days. My changes have been checked in as well.

Cheers.

**Comment by MrN83** [comment]
I have finished proof-reading the translation one last time and checked in. Please initiate a pull request so our work will be available to the public.

Please let me know when you're done so I can close the related issue.

Thanks!

**Comment by NOVAglow** [comment]
Okay, so, what am I supposed to do with my fork?

**Comment by MrN83** [comment]
No worries. I have created the pull request. From now on, it's the job for the original author to publish our work! 

We're all done here, I think. It's been a pleasure working with you :).

Cheers.

P/s: I note that this author has created a similar game/simulation for game theory and someone has translated that into Vietnamese as well. I will check the translation over there when I have time to see if there is anything else to be done.
