### ISSUE TITLE
Simplified Chinese (zh-CN) translation

### ISSUE THREAD

**Issue by olOwOlo** [ncase/crowds#8]
Hi, there. I'm working on it over here:

> https://github.com/illyasviel/crowds

If you want to participate, please let me know, we can translate different section at the same time. 😆

**Comment by appleseed0910** [comment]
Let’s do this!!! I’d like to help. Have you started or not? 
求一下联系方式！

**Comment by olOwOlo** [comment]
@appleseed0910 
I opened issue for my fork.

**Comment by appleseed0910** [comment]
Yeah I’ve seen that. But I didn’t see the copy file of the index.html yet. (I guess you prob just haven’t pushed it?)
Could you plz give me your contact info for distribution and standardize the special terms in the contents?
